-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 22:14:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `isManager` TINYINT NOT NULL,
  PRIMARY KEY (`idEmployee`, `idPerson`),
  INDEX `fk_Employee_Person1_idx` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `age` INT NOT NULL,
  `sex` CHAR(1) NOT NULL,
  PRIMARY KEY (`idCustomer`, `idPerson`),
  INDEX `fk_Customer_Person1_idx` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Person1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `idDoctor` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `licenseNum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDoctor`, `idPerson`),
  INDEX `fk_Doctor_Person1_idx` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Person1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `numInStock` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StockItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StockItem` (
  `idStockItem` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `expirationDate` DATE NOT NULL,
  PRIMARY KEY (`idStockItem`, `idProduct`),
  INDEX `fk_StockItem_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_StockItem_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescription` (
  `idPrecription` INT NOT NULL,
  `idDoctor` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `filled` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  `expirationDate` DATE NOT NULL,
  PRIMARY KEY (`idPrecription`, `idDoctor`, `idCustomer`, `idProduct`),
  INDEX `fk_Prescription_Doctor1_idx` (`idDoctor` ASC) VISIBLE,
  INDEX `fk_Prescription_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_Prescription_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Doctor1`
    FOREIGN KEY (`idDoctor`)
    REFERENCES `mydb`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Supplier` (
  `idProduct` INT NOT NULL,
  `idSupplier` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `idSupplier`),
  INDEX `fk_Product_has_Supplier_Supplier1_idx` (`idSupplier` ASC) VISIBLE,
  INDEX `fk_Product_has_Supplier_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Supplier_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Supplier_Supplier1`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idEmployee` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  `totalCost` FLOAT NOT NULL,
  `datePlaced` DATE NULL,
  `dateReceived` DATE NULL,
  PRIMARY KEY (`idEmployee`, `idProduct`),
  INDEX `fk_Order_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
